set_property PACKAGE_PIN K17 [get_ports iClk]
set_property PACKAGE_PIN V12 [get_ports iRs]
set_property PACKAGE_PIN M14 [get_ports oGPIO]
set_property PACKAGE_PIN W16 [get_ports oRs]
set_property IOSTANDARD LVCMOS18 [get_ports iRs]
set_property IOSTANDARD LVCMOS18 [get_ports oGPIO]
set_property IOSTANDARD LVCMOS18 [get_ports oRs]
set_property IOSTANDARD LVCMOS18 [get_ports iClk]
