@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Sep 27 14:40:46 -0500 2021
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 092212ac5365430da6e156c640678d5e --incr --debug typical --relax --mt 2 -L grlib -L techmap -L gaisler -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot grlib_tester_behav xil_defaultlib.grlib_tester xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 092212ac5365430da6e156c640678d5e --incr --debug typical --relax --mt 2 -L grlib -L techmap -L gaisler -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot grlib_tester_behav xil_defaultlib.grlib_tester xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
