set_property SRC_FILE_INFO {cfile:C:/Users/Bklolo/Desktop/Senior_Proj/FPGA/Vivado_Project/FPGA_Project/FPGA_Project.srcs/constrs_1/new/Constraints2.xdc rfile:../../../FPGA_Project.srcs/constrs_1/new/Constraints2.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K17 [get_ports iClk]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V12 [get_ports iRs]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports oGPIO]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W16 [get_ports oRs]
